sudo: true
language: bash

matrix:
    include:
        - os: linux
        - os: osx

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install bats; brew link --force bats; fi

script: make all

after_success:
    - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $LOGS_WEBHOOK

after_failure:
    - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure $LOGS_WEBHOOK
